INSERT INTO `Categorias`(`CatNome`, `CatGrupo`, `CatSubGrupo`) VALUES ('DIVERSOS', 'GERAIS', 'INDIFERENTE');
INSERT INTO `Categorias`(`CatNome`, `CatGrupo`, `CatSubGrupo`) VALUES ('DIVERSOS', 'GERAIS', NULL);
INSERT INTO `Categorias`(`CatNome`, `CatGrupo`, `CatSubGrupo`) VALUES ('VINHO TINTO', 'BEBIDAS', 'VINHOS E ESPUMANTES');
INSERT INTO `Categorias`(`CatNome`, `CatGrupo`, `CatSubGrupo`) VALUES ('AGUARDENTE', 'BEBIDAS', 'DESTILADOS');
INSERT INTO `Categorias`(`CatNome`, `CatGrupo`, `CatSubGrupo`) VALUES ('CONHAQUE', 'BEBIDAS', 'DESTILADOS');
INSERT INTO `Categorias`(`CatNome`, `CatGrupo`, `CatSubGrupo`) VALUES ('LICOR', 'BEBIDAS', 'DESTILADOS');
INSERT INTO `Categorias`(`CatNome`, `CatGrupo`, `CatSubGrupo`) VALUES ('WISKY', 'BEBIDAS', 'DESTILADOS');
INSERT INTO `Categorias`(`CatNome`, `CatGrupo`, `CatSubGrupo`) VALUES ('VODKA', 'BEBIDAS', 'DESTILADOS');
INSERT INTO `Categorias`(`CatNome`, `CatGrupo`, `CatSubGrupo`) VALUES ('CERVEJAS', 'BEBIDAS', 'CERVEJAS');
INSERT INTO `Categorias`(`CatNome`, `CatGrupo`, `CatSubGrupo`) VALUES ('REFRIGERANTES', 'BEBIDAS', 'REFRIGERANTES');
INSERT INTO `Categorias`(`CatNome`, `CatGrupo`, `CatSubGrupo`) VALUES ('ÁGUA', 'BEBIDAS', 'ÁGUA');
INSERT INTO `Categorias`(`CatNome`, `CatGrupo`, `CatSubGrupo`) VALUES ('SUCOS', 'BEBIDAS', 'SUCOS');
INSERT INTO `Categorias`(`CatNome`, `CatGrupo`, `CatSubGrupo`) VALUES ('CAFÉS/CHÁS', 'MERCEARIA', 'CAFÉS/CHÁS');
INSERT INTO `Categorias`(`CatNome`, `CatGrupo`, `CatSubGrupo`) VALUES ('BALAS', 'BOMBONIERE', 'BALAS E AFINS');
INSERT INTO `Categorias`(`CatNome`, `CatGrupo`, `CatSubGrupo`) VALUES ('PASTILHAS', 'BOMBONIERE', 'BALAS E AFINS');
INSERT INTO `Categorias`(`CatNome`, `CatGrupo`, `CatSubGrupo`) VALUES ('PIRULITOS', 'BOMBONIERE', 'BALAS E AFINS');
INSERT INTO `Categorias`(`CatNome`, `CatGrupo`, `CatSubGrupo`) VALUES ('AVES', 'CARNES', 'AVES');
INSERT INTO `Categorias`(`CatNome`, `CatGrupo`, `CatSubGrupo`) VALUES ('CARNES BOVINAS', 'CARNES', 'CARNES BOVINAS');
INSERT INTO `Categorias`(`CatNome`, `CatGrupo`, `CatSubGrupo`) VALUES ('CARNES SUÍNAS', 'CARNES', 'CARNES SUÍNAS E OVINAS');
INSERT INTO `Categorias`(`CatNome`, `CatGrupo`, `CatSubGrupo`) VALUES ('CARNES OVINAS', 'CARNES', 'CARNES SUÍNAS E OVINAS');
INSERT INTO `Categorias`(`CatNome`, `CatGrupo`, `CatSubGrupo`) VALUES ('PEIXES', 'CARNES', 'PEIXES');
INSERT INTO `Categorias`(`CatNome`, `CatGrupo`, `CatSubGrupo`) VALUES ('VINHO BRANCO', 'BEBIDAS', 'VINHOS E ESPUMANTES');
